# Generated by Django 3.2 on 2023-01-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('tabagism', models.BooleanField(default=False, verbose_name='Fumante')),
                ('alcoholic', models.BooleanField(default=False, verbose_name='Uso de alcool')),
                ('work_out', models.CharField(blank=True, max_length=150, verbose_name='Pratica exercícios')),
                ('dst', models.CharField(blank=True, max_length=150, null=True, verbose_name='Doença sexualmente transmissíveis')),
                ('illicit_substances', models.CharField(blank=True, max_length=150, null=True, verbose_name='Substâncias Ilícitas')),
                ('familiar_history', models.TextField(blank=True, null=True, verbose_name='Histórico Familiar')),
                ('old_medication', models.TextField(blank=True, null=True, verbose_name='Medicação em uso')),
                ('conduct', models.TextField(blank=True, null=True, verbose_name='Conduta')),
                ('patiente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.patiente')),
            ],
        ),
    ]
