# Generated by Django 3.2 on 2023-01-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('alegations', models.TextField(blank=True, null=True, verbose_name='Queixa Principal')),
                ('medication', models.TextField(blank=True, null=True, verbose_name='Medicação')),
                ('exams', models.TextField(blank=True, null=True, verbose_name='Exames')),
                ('patiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='core.patiente')),
            ],
        ),
    ]
