# Generated by Django 3.2 on 2023-01-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('medication', models.TextField(blank=True, null=True, verbose_name='Medicação')),
                ('exams', models.TextField(blank=True, null=True, verbose_name='Exames')),
            ],
        ),
    ]
