# Generated by Django 3.2 on 2023-01-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_prescription_patiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='observations',
        ),
        migrations.AddField(
            model_name='prescription',
            name='alegations',
            field=models.TextField(blank=True, null=True, verbose_name='Queixa Principal'),
        ),
    ]
