# Generated by Django 3.2 on 2023-01-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('birth', models.DateField(verbose_name='Nascimento')),
                ('profession', models.CharField(blank=True, max_length=50, verbose_name='Profissão')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default='N', max_length=1, verbose_name='Sexo')),
                ('cel', models.CharField(blank=True, max_length=11, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Endereço')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patiente',
                'verbose_name_plural': 'Patientes',
            },
        ),
    ]
