# Generated by Django 3.2 on 2023-01-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiente',
            name='gender',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default='N', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='patiente',
            name='profession',
            field=models.CharField(blank=True, max_length=50, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='patiente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
